### ISSUE TITLE
index and meta process error

### ISSUE THREAD

**Issue by Jiam1ng** [Teichlab/cellphonedb#131]
Thanks for your amazing work, I was using cellphonedb to analyze my dataset and encouter erros below:
`File "/data5/lijiaming/tools/cpdb-venv/lib/python3.7/site-packages/pandas/core/indexing.py", line 2009, in _valie_integer`
`    raise IndexError("single positional indexer is out-of-bounds")`
`IndexError: single positional indexer is out-of-bounds`

`During handling of the above exception, another exception occurred:`

...
`File "/data5/lijiaming/tools/cpdb-venv/lib/python3.7/site-packages/cellphonedb/src/core/preprocessors/method_precessors.py", line 35, in meta_preprocessor`
 `   raise ProcessMetaException`
`cellphonedb.src.core.exceptions.ProcessMetaException.ProcessMetaException: Error processing Meta data`

I think the format of my file is just like the test file, and the numbers of row of meta file and column of count file are consistent.
wonder if there any solution?

**Comment by biolofist** [comment]
I had the same issue and it was solved by changing the delimiter on my data; csv worked great

**Comment by mvento** [comment]
Hi @Jiam1ng, 

Did you fix it? Please, send us the input data if it didn't work.

Best

**Comment by Jiam1ng** [comment]
Hi Miquel,


I'm really sorry for not replying, it's likelly that there is something wrong with my mailbox. I have also send this error to the sequencing company, they re-send me the raw data, and it works fine, so I think there may be some mistakes during the data conveying last time. The error is fixed now, really thanks for you kind help, and sorry again for not replying you immediately.


Best regards,


Jiaming


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Miquel"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月18日(星期二) 凌晨0:50
收件人:&nbsp;"Teichlab/cellphonedb"<cellphonedb@noreply.github.com&gt;;
抄送:&nbsp;"李嘉明"<825496222@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Teichlab/cellphonedb] index and meta process error (#131)




Hi @Jiam1ng,
 
Did you fix it? Please, send us the input data if it didn't work.
 
Best

**Comment by mvento** [comment]
Hi @Jiam1ng, 

Perfect! Thanks for using CellPhoneDB.

Best

**Comment by wangjiawen2013** [comment]
> I had the same issue and it was solved by changing the delimiter on my data; csv worked great

I met this error and how to change the delimiter of my meta.csv?

**Comment by Biglinboy** [comment]
@mvento 
I had the same issue when I was using cellphonedb to analyze my dataset and encouter erros below:
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
cellphonedb.src.core.exceptions.ProcessMetaException.ProcessMetaException: Error processing Meta data

The numbers of row of meta file and column of count file are consistent. What is the reason for this?

**Comment by PernilleYR** [comment]
I have the same issue, I tried both .txt or .csv and it doesn't solve the problem. 
Weirdly it works perfectly fine with other dataset that I processed exactly the same way. 
Any idea...?

Here is the error: 
[ ][CORE][09/04/21-15:33:30][INFO] Launching Method cpdb_statistical_analysis_launcher
[ ][APP][09/04/21-15:33:30][ERROR] Unexpected error
Traceback (most recent call last):
  File "/Users/pernillerainer/cpdb/lib/python3.7/site-packages/cellphonedb/src/core/preprocessors/method_preprocessors.py", line 28, in meta_preprocessor
    meta = pd.DataFrame(data={'cell_type': meta_raw.iloc[:, 1]})
  File "/Users/pernillerainer/cpdb/lib/python3.7/site-packages/pandas/core/indexing.py", line 873, in __getitem__
    return self._getitem_tuple(key)
  File "/Users/pernillerainer/cpdb/lib/python3.7/site-packages/pandas/core/indexing.py", line 1443, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/Users/pernillerainer/cpdb/lib/python3.7/site-packages/pandas/core/indexing.py", line 702, in _has_valid_tuple
    self._validate_key(k, i)
  File "/Users/pernillerainer/cpdb/lib/python3.7/site-packages/pandas/core/indexing.py", line 1352, in _validate_key
    self._validate_integer(key, axis)
  File "/Users/pernillerainer/cpdb/lib/python3.7/site-packages/pandas/core/indexing.py", line 1437, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pernillerainer/cpdb/lib/python3.7/site-packages/cellphonedb/src/api_endpoints/terminal_api/method_terminal_api_endpoints/method_terminal_commands.py", line 144, in statistical_analysis
    subsampler,
  File "/Users/pernillerainer/cpdb/lib/python3.7/site-packages/cellphonedb/src/local_launchers/local_method_launcher.py", line 64, in cpdb_statistical_analysis_local_method_launcher
    subsampler
  File "/Users/pernillerainer/cpdb/lib/python3.7/site-packages/cellphonedb/src/core/methods/method_launcher.py", line 50, in cpdb_statistical_analysis_launcher
    meta = method_preprocessors.meta_preprocessor(raw_meta)
  File "/Users/pernillerainer/cpdb/lib/python3.7/site-packages/cellphonedb/src/core/preprocessors/method_preprocessors.py", line 35, in meta_preprocessor
    raise ProcessMetaException
cellphonedb.src.core.exceptions.ProcessMetaException.ProcessMetaException: Error processing Meta data

Thanks! 

Best

**Comment by prete** [comment]
Hi @PernilleYR could you please provide:
- the command you used to launch CellphoneDB
- your meta file or a sample of it

Thanks!

**Comment by PernilleYR** [comment]
Hi @prete, 

Thanks for your answer! 

Here is a sample of the metadata: 
[metadata_example.txt](https://github.com/Teichlab/cellphonedb/files/6403677/metadata_example.txt)

And the command:
cellphonedb method statistical_analysis data/metadata_example.txt data/normdata_EP0.csv --output-path EP0/

I also tried to use a .csv but it also didn't work, even if I tried other datasets and it worked perfectly

Thank you so much for having a look, let me know if you need more info, 

Best, 

Pernille

**Comment by Genki-YAN** [comment]
I also met this error and checked my files. I found there was a line which not split by a tab.
